### ISSUE TITLE
Synology NAS Configuration

### ISSUE THREAD

**Issue by Aleziss** [ChrisRomp/hamclock-docker#10] opened 2024-02-16 09:19 UTC
Hi Chris,

I did read your instructions and I think I have been able to install your docker project on my synology nas docker.

There is one issue though, it seems there is an error when I try to set the center map and I am not sure what could be wrong.

If you have some spare time and would like to help, it would be appreciated.

Thanks 

Claude

**Comment by Aleziss** [comment] 2024-02-16 09:21
![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/6aaf495c-2719-4796-ae29-da8653bb2338)

images found in the registry of the docker control center of the synology nas.

**Comment by Aleziss** [comment] 2024-02-16 11:57
![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/6df01d87-e58c-4c4f-8a77-abd88f0b4085)

Everything else in the config seems to be working well exept that error.

Thanks !

**Comment by Aleziss** [comment] 2024-02-16 12:32
[hamclock-web-1.zip](https://github.com/ChrisRomp/hamclock-docker/files/14310981/hamclock-web-1.zip)

This is the log, if you have a chance to consult it and pinpoint where the issue is !

Thank you !

**Comment by ChrisRomp** [comment] 2024-02-16 16:49
Hi @Aleziss - I don't see anything obviously out of the ordinary from your logfile, but based on some of the earlier (deleted?) messages, I'm not sure if you have the Docker image correct. It should be: `ghcr.io/chrisromp/hamclock-docker:latest`.

I don't have a Synology NAS, but based on [their documentation](https://kb.synology.com/en-us/DSM/help/Docker/docker_container?version=6), once you have the image downloaded it should figure out the rest from the image's [Dockerfile](https://github.com/ChrisRomp/hamclock-docker/blob/main/Dockerfile), including the TCP ports and volume mount. But if you need to modify that, it should be under Advanced Settings.

HamClock exposes two TCP ports:
- `8080` - used for the REST API and sending commands to HamClock
- `8081` - used for accessing HamClock via the web at `[synology-name]:8081/live.html`

The HamClock image I've configured only needs one volume mount:
- `/root/.hamclock` - used for persisting your HamClock settings. Synology's default local path ("File/Folder") for this should be fine as long as the "Mount path" remains `/root/.hamclock`.

If you have another container running that is already using 8080 or 8081 (pretty common ports for many apps), it may map those to different ports on your Synology. Hopefully it tells you this, or you can find it under Advanced Settings.

Alternatively, you can try to follow this blog and use Docker Compose. [Here is a working Docker Compose file](https://github.com/ChrisRomp/hamclock-docker/blob/main/examples/docker-compose.yaml) for my build of HamClock.

For the error "`Err`" you're seeing in the configuration, that field is where the world map will be centered. I set mine to 90W since that's approximately the western US. You can base it off of the east/west location of your QTH (home location).

**Comment by Aleziss** [comment] 2024-02-17 05:17
Hi Chris, thanks so much for taking time to reply and help.

So I did check that the docker image point to the right url and it is, I did copy as per your instructions.

The only thing I have change is the data folder but I am not sure if this is why it create an issue...

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/3a3a994e-caf4-4e84-a09c-f6956a581770)

As for the 'Err', regardless of the coordinates I enter, it never works and always display 'Err' when I hit the DONE button. I even tried yours and it does the same. On my end, I usually use 0E since I am EST. 

I did delete everything and tried again, everything download properly and start correctly. It is when I try to configure my callsign, locator and map centering that it does not seem to be working. After that happend, I can't complete the configuration and it gets stuck there.

Thanks again for your help, it's really appreciated. I am almost there but I still cannot pinpoint what the issue is.

**Comment by ChrisRomp** [comment] 2024-02-17 05:25
The error when saving the settings may be related to the volume mapping for your container. If it can't write to its file, then it will likely show an error.

What jumps out at me is you're changing the mount path and disregarding the volume definition at the end of the compose file. You also changed `/root/.hamclock` to `/data` but that won't work.  If `/volume1/docker/hamclock/data` is the path on your Synology NAS, then we can skip the docker volume definition at the bottom and change the volume mount to:

`/volume1/docker/hamclock/data:/root/.hamclock`

Please give that a try. Full `docker-compose.yaml` for your configuration:

```yaml
version: "3"
services:
  web:
    image: ghcr.io/chrisromp/hamclock-docker:latest
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
    volumes:
      - /volume1/docker/hamclock/data:/root/.hamclock
    restart: unless-stopped
```

**Comment by Aleziss** [comment] 2024-02-17 05:35
Forgive me, I am new to this, that's why I seek help !

I was trying to get all my docker containers somewhere on the same shared folder. I did verify that it is set to RW and it is.

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/ac9c63b5-fe82-4209-9bcf-8a94a00d19e3)

if you think I should leave everything [as per your your example file](https://github.com/ChrisRomp/hamclock-docker/blob/main/examples/docker-compose.yaml), I will try again and not touch folder configuration. 

The other docker container I run have installed at that shared folder ocation and are working.

Thanks again, really appreciate it !

**Comment by ChrisRomp** [comment] 2024-02-17 05:42
What you're wanting to do is fine. But the format is `synology-path:container-path` and the `container-path` *must* be `/root/.hamclock` because that's where HamClock expects to save its configuration inside of the container.

That's why I changed it to `/volume1/docker/hamclock/data:/root/.hamclock` above. 🙂

**Comment by Aleziss** [comment] 2024-02-17 06:10
Ok, it is the `/root/.hamclock` that I did not grasp it seems.

So I did modify the yaml file [as per your previous instructions](https://github.com/ChrisRomp/hamclock-docker/issues/10#issuecomment-1949656125), everything downloaded properly, container started and upgraded hamclock from 3.04 to 3.05.

This is the only file I see in my shared folder for hamclock

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/ee35d625-1f00-4dd6-88db-6a73a79e047f)


And I am also stuck again with that `Err` when I fill in all the parameters. As soon I press the `DONE` button, this happend.

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/c932866a-2a86-44cb-a3b4-940fad7b17e2)


I've included the json config file of the container and also the log.

If you want to check it out... I am starting to think that it might not just work on Synology NAS but at least I did try !

The container also displays that there is an issue but it does not point me what is the error...

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/09ada4cc-715a-4db1-a962-b58001f32cdd)

Avertissement which means Warning (server is in french).


[hamclock-web-1 (1).zip](https://github.com/ChrisRomp/hamclock-docker/files/14317935/hamclock-web-1.1.zip)


You can be sure that if I/you figure out what is going on with that container, I will do a youtube video on how to make this run on as Synology NAS and credit you for it.

Thanks again for your time and patience !

**Comment by Aleziss** [comment] 2024-02-17 06:33
I just found those unkown users in the `data` folder and I was wondering if it has anything to do with docker ?

I cannot find what are those user numbers but in the permission, everything is denied... If these user are related to docker, maybe that's why I am not able to save if those users do not have any permissions on the `data` folder....


![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/b09224a6-f5d0-4260-b5eb-ede28a8111e7)

**Comment by Aleziss** [comment] 2024-02-17 06:35
If you want to help, we can arrange a meeting on zoom... I have a ham radio zoom room where we could meet there and I would be able to share screen...

**Comment by Aleziss** [comment] 2024-02-17 06:49
Uh ! anything with `E` as center map localisation does NOT work.

I did try with your 90W and it DOES work !!!!

So I wonder what is going on with this ???


I did enter `0W` and it started and look like this : 

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/febcb5f9-fc73-4f99-847e-d6235846c952)

**Comment by Aleziss** [comment] 2024-02-17 07:31
So after testing, each time I return to the hamclock setup, there is always an issue with the `Map centir Ing` setting, configuration open directly on `Page 4` and even though I did put 0W at first, when I return it displays again `0E` which cause `Err` to happend again.

The rest of the configuration seem to be retain and does not seem to cause any problems...

I am wondering if there might be something wrong with the actual code when it is run on Synology NAS ?

**Comment by Aleziss** [comment] 2024-02-18 01:44
Hi Chris,

I deleted all my previous attempt in Container Manager and started from scratch.

I did a new folder where all my docker-compose files will reside for all projects now, `volume1/docker/projects/hamclock-compose`.

Using your instructions, I also removed the `data` folder and only set to `volume1/docker/hamclock/root/.hamclock`.

I did create a new Project in Container Manager that resides in `volume1/docker/projects/hamclock-compose/` with the following code:

```
version: "3"
services:
  web:
    image: ghcr.io/chrisromp/hamclock-docker:latest
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
    volumes:
      - /volume1/docker/hamclock:/root/.hamclock
    restart: unless-stopped
```

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/1382578b-ea43-46f3-9fd3-e005373aa62b)


Once the Project is done, I simply run the Project and everything download, install and update by itself.

The only thing NOT working is that `Map center Ing:` with `Err` regardles of what coordinate I enter. The only coordinate that make `hamclock-docker` start is when I input `0W`. All other parameters are kept.

If I restart the Container, as soon I go the the hamclock url, it goes back to settings page 4 with `Err` showing up again.

Should I see data in `/volume1/docker/hamclock:/root/.hamclock` ? Because it is totally empty folder. I am not sure if it is because of the `.` in your folder `.hamclock` that does not work with Synology NAS...

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/0fb9250d-4431-4276-870b-b4177c690dc4)


![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/2d96287d-8ad4-4f3f-b8fd-aef83277acd6)


Aside that `Map center Ing: Err` issue, it sure does work from Synology NAS.


Here is a snapshot taken just before I change the value from `0E` to `0W` :  

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/ef8c3f7c-e4e3-4681-a3b7-5f77ec79574f)


I don't know what to check anymore at this point !

If you have a clue on what could be wrong, let me know ! It would be a nice project to run out of Synology NAS systems.

Claude

**Comment by ChrisRomp** [comment] 2024-02-18 02:15
I haven't forgotten about you, don't worry. Just busy with family so I'll check into this more when I'm able. 🙂

**Comment by Aleziss** [comment] 2024-02-18 03:15
I totally understand Chris, family time 1st ! Thanks for your help !

Claude

**Comment by ChrisRomp** [comment] 2024-02-18 04:52
In your configuration `/volume1/docker/hamclock` acts like a symbolic link (symlink) to `/root/.hamclock` inside of the container. So a file in the Docker container at `/root/.hamclock` would show up in your NAS at `/volume1/docker/hamclock`.

The NAS folder `/volume1/docker/hamclock/root/.hamclock` would translate to `/root/.hamclock/root/.hamclock` in the container.

The other error I don't suspect is the real problem; that's probably related to something for HamClock's ability to connect to wifi, which you should not need to do in a container.

Ooooohhhhh! Did you configure wifi in the container? Don't. The Docker container already has network access; it doesn't have a wifi interface.

**Comment by ChrisRomp** [comment] 2024-02-18 05:00
I was able to reproduce your wifi error, but that's not the cause of the map center error, which I've also reproduced. I'll do some more testing. This might be a HamClock bug.

**Comment by ChrisRomp** [comment] 2024-02-18 05:05
Ok.... 

1. Clear your wifi settings (erase SSID).
2. Set map center to 1W for now. It seems ok with this and doesn't return to settings on every boot.

I'm going to follow up with the HamClock developer on this issue. I'll leave this GitHub issue for tracking.

**Comment by Aleziss** [comment] 2024-02-18 05:14
hmm... erase SSID ? from the computer I access hamclock ?

**Comment by Aleziss** [comment] 2024-02-18 05:19
center map at 1W seem to be working and not causing issue when the container restart.

**Comment by ChrisRomp** [comment] 2024-02-18 05:24
"Erase SSID" - In HamClock setup on Page 1, ensure there's nothing in the WiFi. If it says "No" then you're fine. The warning you showed in your logs before about `wpa_supplicant.conf` is for saving wifi configuration from inside of HamClock. Again, it uses your Docker host's network.

**Comment by Aleziss** [comment] 2024-02-18 05:28
wifi was turned off already... but when I did turn it on, I could see there was an SSID and a password setup. I deleted and put back to `No`.

![image](https://github.com/ChrisRomp/hamclock-docker/assets/57082992/830be357-e0b4-4039-acdb-2a347c63c016)

**Comment by ChrisRomp** [comment] 2024-02-18 05:31
Alright, I think you should be good to go, then. I've emailed Elwood about the error setting anything east of `1W` and also asked him about that WiFi that shows up by default (I saw that, too).

When I hear back on the `0E` issue I'll update here and close the issue.-

**Comment by Aleziss** [comment] 2024-02-18 05:33
Awesome, thank you Chris, I'll wait before publishing a tutorial on how to do this on Synology NAS. I would like to double verify the docker-compose and procedures with you when the time arise. Awesome support !

**Comment by ChrisRomp** [comment] 2024-02-18 06:44
Elwood isn’t seeing the same map center error for eastern coordinates, so it might be something about how the app is being built in my container. I’ll do some additional testing when time allows.

**Comment by ChrisRomp** [comment] 2024-02-19 22:05
Since this issue is mostly about the Synology setup, I've opened #12 to track the map center issue. I have a fix, but I need to test it some more.

I'm going to close this issue since the Synology issue is resolved. 👍

**Closed by ChrisRomp** 2024-02-19 22:05 UTC
